vaultInit:
  # If configureKubernetesAuth is true, clusterName will be used for the auth
  # engine, secret engine, policy, and role names. If configureKubernetesAuth
  # is not true, this value is ignored.
  clusterName: kubernetes

  # Automatically configure Vault with a Kubernetes type auth engine, kv secret
  # engine, policy, and role.
  configureKubernetesAuth: true

  # Name of the helm deployment
  # TODO: Remove this. Should be able to use .Release.Name instead
  helmDeploymentName: vault-server

  # Do not execute init.sh on pod start. This is useful for debugging the
  # script. To manually execute init.sh, get a shell in the pod and run:
  # `export PAUSE_INIT=false && /bin/bash /tmp/scripts/init.sh`
  pauseInit: false

# Values under vault are passed to the Hashicorp Vault chart.
# https://github.com/hashicorp/vault-helm
vault:
  global:
    openshift: true

  ui:
    enabled: true

  injector:
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
      tag: "0.17.0-ubi"

    agentImage:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.11.2-ubi"

  server:
    dataStorage:
      enabled: true
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.11.2-ubi"
    ha:
      enabled: true
      replicas: 3
      raft:
        enabled: true
    postStart:
      - "/bin/bash"
      - "/tmp/scripts/init.sh"
    route:
      enabled: true
      # !! REPLACE HOST VALUE WITH YOUR VAULT HOSTNAME !!
      host: vault.apps.hub.taco.moe
      tls:
        termination: edge
    volumes:
      - name: init-script
        configMap:
          name: init-script
    volumeMounts:
      - mountPath: /tmp/scripts
        name: init-script
